# Dockerfile.frontend
FROM node:18-alpine

WORKDIR /app

# Копируем зависимости и устанавливаем
COPY frontend/package*.json ./
RUN npm install

# Копируем код
COPY frontend/ .

# Собираем и запускаем dev-сервер
CMD ["npm", "run", "dev", "--host", "0.0.0.0"]